version: "3.8"

services:
  app:
    build: .
    ports:
      - "${SERVER_ADDR_PORT}:${SERVER_ADDR_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"